### ISSUE TITLE
can't get a distribution group working.

### ISSUE THREAD

**Issue by michael23505** [SebastianObi/LXMF-Tools#5]
using linux, and running the file for lxmf distribution group extended. but nothing works.

**Comment by Terramoto** [comment]
I believe the encoding in the data.cfg and config.cfg breaks when the script tries to read it.
Other than that the extended version should work just fine.
The other versions appear to have the wrong bytecode for command interpretation set in MSG_FIELD_COMMANDS_EXECUTE.
according to [LXMF](https://github.com/markqvist/LXMF/blob/96dddf1b3a0328f22b59ac7d4fcc8193d9884a44/LXMF/LXMF.py#L16) it should be 0x09 and then if you send the commands in command mode, they should be interpreted.

**Comment by michael23505** [comment]
here is the output i get when i run the program. i hope it helps.

./lxmf_distribution_group_extended.py
/home/b-5363/./lxmf_distribution_group_extended.py:3431: SyntaxWarning: invalid escape sequence '\w'
  data = re.sub(r'^#?'+key+'( +)?=( +)?(\w+)?', key+" = "+value, data, count=1, flags=re.MULTILINE)
/home/b-5363/./lxmf_distribution_group_extended.py:3441: SyntaxWarning: invalid escape sequence '\w'
  data = re.sub(r'^#?'+key+'( +)?=( +)?(\w+)?', key+" = "+value, data, count=1, flags=re.MULTILINE)
[2025-01-04 20:47:44] [Notice] LXMF - No Primary Identity file found, creating new...
[2025-01-04 20:47:44] [Notice] LXMF - Created new Primary Identity <a8475f39f056ebb3ddc61494ae8ec120>
Traceback (most recent call last):
  File "/home/b-5363/./lxmf_distribution_group_extended.py", line 5802, in <module>
    main()
  File "/home/b-5363/./lxmf_distribution_group_extended.py", line 4376, in main
    setup(path=params.path, path_rns=params.path_rns, path_log=params.path_log, loglevel=params.loglevel, service=params.service)
  File "/home/b-5363/./lxmf_distribution_group_extended.py", line 4239, in setup
    LXMF_CONNECTION = lxmf_connection(
                      ^^^^^^^^^^^^^^^^
  File "/home/b-5363/./lxmf_distribution_group_extended.py", line 237, in __init__
    self.message_router = LXMF.LXMRouter(identity=self.identity, storagepath=self.storage_path)
                          ^^^^^^^^^^^^^^
AttributeError: module 'LXMF' has no attribute 'LXMRouter'

**Comment by Terramoto** [comment]
> here is the output i get when i run the program. i hope it helps.
> 
> LXMF.LXMRouter(identity=self.identity, storagepath=self.storage_path) ^^^^^^^^^^^^^^ AttributeError: module 'LXMF' has no attribute 'LXMRouter'

What is the version of the LXMF package you have installed?

**Comment by Terramoto** [comment]
> 0.5.8

I have the same version but i'm not getting the error. That error is usually associated with a different version of the package or code.

I also can't seem to find the LXMF_CONNECTION = lxmf_connection line mentioned in the error which suggests you might be running a different version?

T

**Comment by SebastianObi** [comment]
I cleaned up the code for lxmf_distribution, this was old and no more needed. You should only use lxmf_distribution_group_extended or lxmf_distribution_group_minimal.

At the moment i'm still on vacation, therefore i have not seen your messages.

I try to find some time soon to help you.

**Comment by SebastianObi** [comment]
It should work now, i tried it with nomadnet. The "command mode" is not interpreted. It only works with normal text messages.
